In [1]:
import pandas as pd

In [2]:
files = [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912
        ,202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012]

In [3]:
y201901_df = pd.read_csv(f"./data/JC-{files[0]}-citibike-tripdata.csv")

In [4]:
y201902_df = pd.read_csv(f"./data/JC-{files[1]}-citibike-tripdata.csv")

In [5]:
y201903_df = pd.read_csv(f"./data/JC-{files[2]}-citibike-tripdata.csv")

In [6]:
y201904_df = pd.read_csv(f"./data/JC-{files[3]}-citibike-tripdata.csv")

In [7]:
y201905_df = pd.read_csv(f"./data/JC-{files[4]}-citibike-tripdata.csv")

In [8]:
y201906_df = pd.read_csv(f"./data/JC-{files[5]}-citibike-tripdata.csv")

y201907_df = pd.read_csv(f"./data/JC-{files[6]}-citibike-tripdata.csv")

y201908_df = pd.read_csv(f"./data/JC-{files[7]}-citibike-tripdata.csv")

y201909_df = pd.read_csv(f"./data/JC-{files[8]}-citibike-tripdata.csv")

y201910_df = pd.read_csv(f"./data/JC-{files[9]}-citibike-tripdata.csv")

y201911_df = pd.read_csv(f"./data/JC-{files[10]}-citibike-tripdata.csv")

y201912_df = pd.read_csv(f"./data/JC-{files[11]}-citibike-tripdata.csv")

y202001_df = pd.read_csv(f"./data/JC-{files[12]}-citibike-tripdata.csv")

y202002_df = pd.read_csv(f"./data/JC-{files[13]}-citibike-tripdata.csv")

y202003_df = pd.read_csv(f"./data/JC-{files[14]}-citibike-tripdata.csv")

y202004_df = pd.read_csv(f"./data/JC-{files[15]}-citibike-tripdata.csv")

y202005_df = pd.read_csv(f"./data/JC-{files[16]}-citibike-tripdata.csv")

y202006_df = pd.read_csv(f"./data/JC-{files[17]}-citibike-tripdata.csv")

y202007_df = pd.read_csv(f"./data/JC-{files[18]}-citibike-tripdata.csv")

y202008_df = pd.read_csv(f"./data/JC-{files[19]}-citibike-tripdata.csv")

y202009_df = pd.read_csv(f"./data/JC-{files[20]}-citibike-tripdata.csv")

y202010_df = pd.read_csv(f"./data/JC-{files[21]}-citibike-tripdata.csv")

y202011_df = pd.read_csv(f"./data/JC-{files[22]}-citibike-tripdata.csv")

y202012_df = pd.read_csv(f"./data/JC-{files[23]}-citibike-tripdata.csv")

In [9]:
y201901_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19671,853,2019-01-26 06:40:17.3320,2019-01-26 06:54:30.8880,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26293,Subscriber,1977,1
19672,936,2019-01-27 06:36:20.6400,2019-01-27 06:51:57.1460,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26291,Subscriber,1977,1
19673,653,2019-01-27 21:14:08.5460,2019-01-27 21:25:01.6170,3694,Jackson Square,40.711130,-74.078900,3677,Glenwood Ave,40.727551,-74.071061,26188,Customer,1998,2
19674,960,2019-01-29 06:15:26.5880,2019-01-29 06:31:26.7300,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26196,Subscriber,1977,1
19675,1109,2019-01-30 06:30:03.6050,2019-01-30 06:48:33.2760,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26242,Subscriber,1977,1

In [10]:
y201902_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,142,2019-02-01 15:35:02.0820,2019-02-01 15:37:24.1360,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29677,Subscriber,1963,1
1,223,2019-02-01 17:00:46.8900,2019-02-01 17:04:30.5500,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26234,Subscriber,1992,2
2,106,2019-02-01 17:08:01.3260,2019-02-01 17:09:47.4400,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29588,Subscriber,1960,1
3,370,2019-02-01 17:09:31.2100,2019-02-01 17:15:41.6550,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29250,Subscriber,1976,1
4,315,2019-02-01 17:19:53.2490,2019-02-01 17:25:09.1400,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,29586,Subscriber,1980,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18560,367,2019-02-21 12:05:05.2680,2019-02-21 12:11:13.2210,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26189,Subscriber,1983,1
18561,497,2019-02-21 17:45:00.4510,2019-02-21 17:53:18.1580,3694,Jackson Square,40.711130,-74.078900,3679,Bergen Ave,40.722104,-74.071455,29296,Subscriber,1985,1
18562,959,2019-02-25 06:17:31.9310,2019-02-25 06:33:31.4950,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29673,Subscriber,1977,1
18563,936,2019-02-26 06:14:45.4170,2019-02-26 06:30:21.8750,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29672,Subscriber,1977,1
18564,822,2019-02-26 15:45:20.5370,2019-02-26 15:59:02.6070,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26189,Subscriber,1983,2

In [11]:
y201903_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,306,2019-03-01 06:47:08.2110,2019-03-01 06:52:14.7150,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26272,Subscriber,1989,1
1,123,2019-03-01 07:30:53.0220,2019-03-01 07:32:56.7770,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26192,Subscriber,1966,1
2,328,2019-03-01 08:18:30.4030,2019-03-01 08:23:59.0590,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,26226,Subscriber,1971,2
3,95,2019-03-01 11:04:47.2020,2019-03-01 11:06:22.8130,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26204,Subscriber,1985,1
4,169,2019-03-01 11:51:29.4170,2019-03-01 11:54:19.2120,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29449,Subscriber,1971,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23601,916,2019-03-29 13:38:36.1750,2019-03-29 13:53:53.0100,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29277,Subscriber,1988,1
23602,661,2019-03-29 15:29:18.7510,2019-03-29 15:40:20.2510,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26235,Subscriber,1983,2
23603,577,2019-03-30 13:43:09.2090,2019-03-30 13:52:46.7140,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,29596,Subscriber,1988,1
23604,585,2019-03-31 08:33:21.5200,2019-03-31 08:43:06.7520,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,26192,Subscriber,1988,1
23605,914,2019-03-31 14:59:32.3980,2019-03-31 15:14:46.8480,3694,Jackson Square,40.711130,-74.078900,3185,City Hall,40.717733,-74.043845,29634,Subscriber,1993,2

In [12]:
y201904_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,107,2019-04-01 07:48:04.7540,2019-04-01 07:49:52.3590,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29536,Subscriber,1966,1
1,493,2019-04-01 12:41:09.6540,2019-04-01 12:49:23.0290,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,26191,Customer,1990,1
2,512,2019-04-01 14:27:07.9400,2019-04-01 14:35:40.9370,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1987,2
3,196,2019-04-01 15:07:38.1510,2019-04-01 15:10:54.6260,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26220,Subscriber,1989,1
4,463,2019-04-01 16:19:24.6940,2019-04-01 16:27:08.6450,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,26228,Subscriber,1995,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33051,335,2019-04-27 20:12:13.3830,2019-04-27 20:17:48.5690,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26303,Subscriber,1983,2
33052,679,2019-04-28 13:23:04.7290,2019-04-28 13:34:23.7550,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,29294,Subscriber,1988,1
33053,793,2019-04-29 13:46:39.2540,2019-04-29 13:59:52.2890,3694,Jackson Square,40.711130,-74.078900,3640,Journal Square,40.733670,-74.062500,26275,Subscriber,1991,2
33054,706,2019-04-30 10:47:41.6730,2019-04-30 10:59:28.5910,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,29666,Subscriber,1991,2
33055,721,2019-04-30 19:30:56.2830,2019-04-30 19:42:57.6050,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730897,-74.063913,29609,Subscriber,1988,1

In [13]:
y201905_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36130,792,2019-05-31 23:51:00.1170,2019-06-01 00:04:12.4530,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,26236,Customer,1991,1
36131,779,2019-05-31 23:51:22.7840,2019-06-01 00:04:22.3990,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,29205,Customer,1991,2
36132,347,2019-05-31 23:55:38.3850,2019-06-01 00:01:26.2030,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26179,Subscriber,1989,2
36133,552,2019-05-31 23:56:11.9740,2019-06-01 00:05:24.8810,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29528,Subscriber,1992,1
36134,520,2019-05-31 23:56:25.0240,2019-06-01 00:05:05.4860,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29589,Subscriber,1984,2

In [14]:
y201906_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1
39426,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2
39427,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1
39428,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717733,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1
39429,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1

In [15]:
y201907_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43741,673,2019-07-31 23:39:13.1800,2019-07-31 23:50:26.6520,3681,Grand St,40.715178,-74.037683,3277,Communipaw & Berry Lane,40.714358,-74.066611,26284,Subscriber,1987,1
43742,161,2019-07-31 23:41:24.1110,2019-07-31 23:44:05.4090,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,29570,Subscriber,1998,1
43743,310,2019-07-31 23:47:27.3940,2019-07-31 23:52:37.4870,3195,Sip Ave,40.730897,-74.063913,3678,Fairmount Ave,40.725726,-74.071959,26237,Subscriber,1977,1
43744,137,2019-07-31 23:59:29.9300,2019-08-01 00:01:47.1970,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29121,Subscriber,1993,1
43745,463,2019-07-31 23:59:54.9470,2019-08-01 00:07:37.9750,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29259,Subscriber,1988,1

In [16]:
y201908_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717733,-74.043845,29679,Customer,1997,1
48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [17]:
y201909_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2
2,569,2019-09-01 00:07:13.0020,2019-09-01 00:16:42.8610,3214,Essex Light Rail,40.712774,-74.036486,3184,Paulus Hook,40.714145,-74.033552,29435,Customer,1977,1
3,1380,2019-09-01 00:07:25.3350,2019-09-01 00:30:26.1640,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29509,Subscriber,1965,1
4,1346,2019-09-01 00:07:56.4670,2019-09-01 00:30:22.5440,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29226,Subscriber,1968,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49239,621,2019-09-30 23:11:40.0630,2019-09-30 23:22:01.8370,3194,McGinley Square,40.725340,-74.067622,3191,Union St,40.718211,-74.083639,26245,Subscriber,1962,1
49240,167,2019-09-30 23:19:02.9380,2019-09-30 23:21:50.8290,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29525,Subscriber,1984,1
49241,94,2019-09-30 23:26:24.7470,2019-09-30 23:27:59.2310,3213,Van Vorst Park,40.718489,-74.047727,3483,Montgomery St,40.719420,-74.050990,26317,Subscriber,1958,1
49242,366,2019-09-30 23:49:00.4260,2019-09-30 23:55:06.9620,3638,Washington St,40.724294,-74.035483,3270,Jersey & 6th St,40.725289,-74.045572,29488,Subscriber,1976,1
49243,150,2019-09-30 23:56:30.1980,2019-09-30 23:59:00.6750,3276,Marin Light Rail,40.714584,-74.042817,3213,Van Vorst Park,40.718489,-74.047727,29498,Subscriber,1982,1

In [18]:
y201910_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42248,287,2019-10-31 23:42:25.1120,2019-10-31 23:47:12.6180,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,26160,Subscriber,1987,1
42249,532,2019-10-31 23:48:07.5720,2019-10-31 23:56:59.7280,3187,Warren St,40.721124,-74.038051,3187,Warren St,40.721124,-74.038051,26292,Subscriber,1976,0
42250,202,2019-10-31 23:50:04.3480,2019-10-31 23:53:26.6230,3681,Grand St,40.715178,-74.037683,3185,City Hall,40.717733,-74.043845,26180,Subscriber,1977,1
42251,841,2019-10-31 23:53:24.5280,2019-11-01 00:07:25.8950,3199,Newport Pkwy,40.728745,-74.032108,3483,Montgomery St,40.719420,-74.050990,29655,Subscriber,1958,1
42252,268,2019-10-31 23:53:45.6170,2019-10-31 23:58:13.8980,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,26314,Subscriber,1964,1

In [19]:
y201911_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,260,2019-11-01 00:02:53.8860,2019-11-01 00:07:14.6450,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,26314,Subscriber,1964,1
1,285,2019-11-01 00:05:38.6360,2019-11-01 00:10:24.1930,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,26238,Subscriber,1986,2
2,501,2019-11-01 00:05:43.6310,2019-11-01 00:14:05.4810,3186,Grove St PATH,40.719586,-74.043117,3192,Liberty Light Rail,40.711242,-74.055701,29645,Subscriber,1995,1
3,556,2019-11-01 00:07:57.0550,2019-11-01 00:17:13.9010,3209,Brunswick St,40.724176,-74.050656,3678,Fairmount Ave,40.725726,-74.071959,29221,Customer,1992,1
4,321,2019-11-01 00:11:44.5660,2019-11-01 00:17:05.5930,3273,Manila & 1st,40.721651,-74.042884,3273,Manila & 1st,40.721651,-74.042884,29591,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30792,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1
30793,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1
30794,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1
30795,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1
30796,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1

In [20]:
y201912_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1553,2019-12-01 00:07:13.9360,2019-12-01 00:33:07.6820,3681,Grand St,40.715178,-74.037683,3198,Heights Elevator,40.748716,-74.040443,29462,Subscriber,1980,1
1,416,2019-12-01 00:16:40.4700,2019-12-01 00:23:36.5700,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29610,Subscriber,1956,1
2,294,2019-12-01 00:20:29.7980,2019-12-01 00:25:23.9690,3195,Sip Ave,40.730897,-74.063913,3678,Fairmount Ave,40.725726,-74.071959,26166,Subscriber,1977,1
3,97,2019-12-01 00:21:13.7580,2019-12-01 00:22:51.5970,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,29492,Subscriber,1993,1
4,286,2019-12-01 00:29:58.0230,2019-12-01 00:34:44.2280,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29440,Customer,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
19724,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
19725,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,1
19726,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
19727,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [21]:
y202001_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.3910,2020-01-31 23:38:33.6910,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,1
26016,122,2020-01-31 23:30:59.3670,2020-01-31 23:33:01.6870,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,1
26017,201,2020-01-31 23:42:34.8460,2020-01-31 23:45:55.8780,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,1
26018,300,2020-01-31 23:45:00.6800,2020-01-31 23:50:00.8740,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,2
26019,721,2020-01-31 23:48:35.1700,2020-02-01 00:00:36.4060,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,1

In [22]:
y202002_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22957,262,2020-02-29 23:40:53.1620,2020-02-29 23:45:15.3180,3639,Harborside,40.719252,-74.034234,3214,Essex Light Rail,40.712774,-74.036486,42467,Subscriber,1967,1
22958,216,2020-02-29 23:41:01.3350,2020-02-29 23:44:38.0350,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42377,Subscriber,1958,1
22959,101,2020-02-29 23:45:22.1700,2020-02-29 23:47:03.2970,3214,Essex Light Rail,40.712774,-74.036486,3681,Grand St,40.715178,-74.037683,42485,Subscriber,1967,1
22960,279,2020-02-29 23:47:56.8380,2020-02-29 23:52:36.6400,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42531,Subscriber,1988,1
22961,212,2020-02-29 23:49:18.4510,2020-02-29 23:52:50.7490,3184,Paulus Hook,40.714145,-74.033552,3276,Marin Light Rail,40.714584,-74.042817,42385,Subscriber,1967,1

In [23]:
y202003_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1
17715,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1
17716,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1
17717,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1
17718,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1

In [24]:
y202004_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1

In [25]:
y202005_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,349,2020-05-01 00:09:45.5860,2020-05-01 00:15:35.2930,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42581,Customer,1969,0
1,138,2020-05-01 01:11:22.5280,2020-05-01 01:13:41.2460,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42105,Subscriber,1949,1
2,229,2020-05-01 05:31:29.5350,2020-05-01 05:35:19.2400,3483,Montgomery St,40.719420,-74.050990,3186,Grove St PATH,40.719586,-74.043117,42320,Customer,1984,1
3,261,2020-05-01 05:51:39.3960,2020-05-01 05:56:00.9370,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,42170,Subscriber,1974,2
4,168,2020-05-01 06:06:31.9510,2020-05-01 06:09:20.1410,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,42352,Subscriber,1966,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25072,395,2020-05-31 23:35:50.9460,2020-05-31 23:42:26.5300,3202,Newport PATH,40.727224,-74.033759,3276,Marin Light Rail,40.714584,-74.042817,42250,Subscriber,1992,1
25073,1681,2020-05-31 23:38:30.8240,2020-06-01 00:06:32.0360,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42396,Customer,1997,1
25074,1657,2020-05-31 23:39:07.2680,2020-06-01 00:06:44.5740,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42331,Customer,1987,1
25075,420,2020-05-31 23:45:28.3290,2020-05-31 23:52:28.3680,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,40517,Subscriber,1999,1
25076,87,2020-05-31 23:50:55.8390,2020-05-31 23:52:23.0920,3272,Jersey & 3rd,40.723332,-74.045953,3211,Newark Ave,40.721525,-74.046305,42314,Subscriber,1976,1

In [26]:
y202006_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,Subscriber,1987,1
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,Subscriber,1988,1
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,Subscriber,1987,1
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,Subscriber,1987,1
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,Subscriber,1972,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36916,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0
36917,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0
36918,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0
36919,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0
36920,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2

In [27]:
y202007_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2333,2020-07-01 00:23:19.8220,2020-07-01 01:02:13.2980,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,42579,Customer,1969,0
1,1203,2020-07-01 00:27:45.2420,2020-07-01 00:47:49.1960,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3202,Newport PATH,40.727224,-74.033759,42564,Subscriber,1965,1
2,786,2020-07-01 00:34:17.8680,2020-07-01 00:47:24.6310,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3225,Baldwin at Montgomery,40.723659,-74.064194,42219,Subscriber,1994,1
3,1488,2020-07-01 00:51:07.5310,2020-07-01 01:15:56.0200,3677,Glenwood Ave,40.727551,-74.071061,3194,McGinley Square,40.725340,-74.067622,44424,Subscriber,1995,2
4,2682,2020-07-01 00:51:16.3880,2020-07-01 01:35:58.4590,3191,Union St,40.718211,-74.083639,3193,Lincoln Park,40.724605,-74.078406,42186,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38675,1003,2020-07-31 23:51:37.3790,2020-08-01 00:08:20.6900,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3277,Communipaw & Berry Lane,40.714358,-74.066611,42145,Subscriber,1977,1
38676,165,2020-07-31 23:56:33.6770,2020-07-31 23:59:18.8610,3198,Heights Elevator,40.748716,-74.040443,3196,Riverview Park,40.744319,-74.043991,44334,Subscriber,1991,1
38677,382,2020-07-31 23:56:55.9860,2020-08-01 00:03:18.8390,3209,Brunswick St,40.724176,-74.050656,3275,Columbus Drive,40.718355,-74.038914,42154,Subscriber,1984,1
38678,674,2020-07-31 23:57:58.0150,2020-08-01 00:09:12.0420,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,45366,Customer,1994,2
38679,1007,2020-07-31 23:58:06.3070,2020-08-01 00:14:53.3340,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,42139,Subscriber,1982,1

In [28]:
y202008_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,Subscriber,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42310,Customer,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42346,Customer,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [29]:
y202009_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,222,2020-09-01 00:15:58.6470,2020-09-01 00:19:40.8750,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,45656,Subscriber,1992,1
1,193,2020-09-01 00:49:00.7370,2020-09-01 00:52:14.3640,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,45352,Subscriber,1991,1
2,273,2020-09-01 00:51:44.5870,2020-09-01 00:56:17.7160,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,44424,Subscriber,1969,1
3,1419,2020-09-01 00:52:48.3160,2020-09-01 01:16:28.0490,3203,Hamilton Park,40.727596,-74.044247,3270,Jersey & 6th St,40.725289,-74.045572,42240,Subscriber,1986,1
4,254,2020-09-01 00:56:16.7170,2020-09-01 01:00:31.0870,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,42434,Subscriber,1992,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53828,270,2020-10-13 15:05:35.0860,2020-10-13 15:10:05.3430,3207,Oakland Ave,40.737604,-74.052478,3640,Journal Square,40.733670,-74.062500,44744,Subscriber,1963,2
53829,400,2020-10-13 15:09:03.4890,2020-10-13 15:15:43.9750,3209,Brunswick St,40.724176,-74.050656,3209,Brunswick St,40.724176,-74.050656,45345,Subscriber,1984,1
53830,206,2020-10-13 15:11:34.3500,2020-10-13 15:15:00.5030,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,47019,Subscriber,1993,1
53831,216,2020-10-13 15:11:49.1510,2020-10-13 15:15:25.6930,3195,Sip Ave,40.730897,-74.063913,3225,Baldwin at Montgomery,40.723659,-74.064194,42191,Subscriber,1966,1
53832,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,-74.043117,47255,Subscriber,1991,1

In [30]:
y202010_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30081,1054,2020-10-31 23:32:22.8650,2020-10-31 23:49:57.5320,3198,Heights Elevator,40.748716,-74.040443,3678,Fairmount Ave,40.725726,-74.071959,17231,Customer,1969,0
30082,156,2020-10-31 23:33:22.7310,2020-10-31 23:35:59.4930,3185,City Hall,40.717733,-74.043845,3681,Grand St,40.715178,-74.037683,46532,Subscriber,1981,1
30083,1858,2020-10-31 23:37:01.7010,2020-11-01 00:07:59.7530,3278,Monmouth and 6th,40.725685,-74.048790,3278,Monmouth and 6th,40.725685,-74.048790,42230,Subscriber,1998,1
30084,1809,2020-10-31 23:37:46.1430,2020-11-01 00:07:55.2740,3278,Monmouth and 6th,40.725685,-74.048790,3278,Monmouth and 6th,40.725685,-74.048790,45341,Subscriber,1999,1
30085,395,2020-10-31 23:40:06.3530,2020-10-31 23:46:42.0640,3481,York St,40.716490,-74.041050,3273,Manila & 1st,40.721651,-74.042884,45647,Subscriber,1967,1

In [31]:
y202011_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,756,2020-11-01 00:11:32.6250,2020-11-01 00:24:09.5850,3275,Columbus Drive,40.718355,-74.038914,3225,Baldwin at Montgomery,40.723659,-74.064194,42436,Subscriber,1984,1
1,584,2020-11-01 00:14:20.4820,2020-11-01 00:24:04.7820,3681,Grand St,40.715178,-74.037683,3209,Brunswick St,40.724176,-74.050656,46532,Customer,1969,0
2,403,2020-11-01 00:22:55.8820,2020-11-01 00:29:39.0950,3203,Hamilton Park,40.727596,-74.044247,3483,Montgomery St,40.719420,-74.050990,35139,Subscriber,1980,1
3,498,2020-11-01 00:41:37.4270,2020-11-01 00:49:55.7010,3268,Lafayette Park,40.713464,-74.062859,3213,Van Vorst Park,40.718489,-74.047727,46539,Customer,1969,0
4,151,2020-11-01 00:53:21.2340,2020-11-01 00:55:52.8060,3185,City Hall,40.717733,-74.043845,3276,Marin Light Rail,40.714584,-74.042817,44388,Subscriber,1986,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21270,849,2020-11-30 23:08:40.1870,2020-11-30 23:22:50.0830,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,44742,Subscriber,1996,2
21271,370,2020-11-30 23:09:27.0180,2020-11-30 23:15:37.3330,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,17450,Subscriber,1999,1
21272,341,2020-11-30 23:37:53.0580,2020-11-30 23:43:34.1200,3187,Warren St,40.721124,-74.038051,3202,Newport PATH,40.727224,-74.033759,42528,Subscriber,1991,1
21273,5272,2020-11-30 23:49:31.8650,2020-12-01 01:17:24.2540,3679,Bergen Ave,40.722104,-74.071455,3679,Bergen Ave,40.722104,-74.071455,14657,Customer,1990,1
21274,222,2020-11-30 23:56:52.8310,2020-12-01 00:00:34.8660,3205,JC Medical Center,40.716540,-74.049638,3276,Marin Light Rail,40.714584,-74.042817,42601,Subscriber,1990,1

In [40]:
merged_df = pd.concat(
[y201901_df,
y201902_df,
y201903_df,
y201904_df,
y201905_df,
y201906_df,
y201907_df,
y201908_df,
y201909_df,
y201910_df,
y201911_df,
y201912_df,
y202001_df,
y202002_df, 
y202003_df, 
y202004_df,
y202005_df,
y202006_df,
y202007_df,
y202008_df,
y202009_df,
y202010_df,
y202011_df,
y202012_df], sort=False)

In [42]:
merged_df.reset_index(inplace=True)

In [43]:
merged_df.drop(['index'], axis = 1, inplace = True)

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741744,11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
741745,11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
741746,11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
741747,11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
741748,11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [45]:
merged_df

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741744,11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
741745,11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
741746,11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
741747,11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
741748,11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [46]:
merged_df.to_csv("merged_JC20192020.csv")